### PR TITLE
The start of rspec integration

### PR DESCRIPTION
**Pull request by sdwolf**
Added the travis badge and the setup for rspec specs.

### CODE REVIEW

**Comment by sdwolf** [comment]
Hmm it looks like jruby is not compatible with reek. Its a nice to have gem with similar (but more advanced) output as rubocop but I can live without it for now.

So far I've only used rails_best_practices and rubocop successfully. Let's see what works.

**Comment by sdwolf** [comment]
:beers: test passed.

**Comment by ixti** [comment]
Awesome.

PS I love rubocop as well. Have a bit [different style preferences](https://raw.githubusercontent.com/ixti/dotfiles/master/rubocop.yml), but love it in general :D

**Comment by sdwolf** [comment]
For my own project I follow the "more convention, less configuration" and "new is always better" guidelines but I do belive that if an existing project has a set of coding standards decided than I should follow them regardless of my preference unless there is something that indeed shows a substantial benefit.
I've also experimented with different coding styles over the last year and this can clearly be seen in my code :grin:. 

I will refactor the code to remove all rubocop warnings but that will take some time.

**Comment by ixti** [comment]
I'm OK to go with style you prefer.

**Comment by ixti** [comment]
Linked my rubocop config mostly to emphasize that I really love rubocop ;))

**Pull request merged**
