### PR TITLE
Redmine 3 compatibility

### PR DESCRIPTION
**Pull request by sdwolf**
This PR contains all changes from [marius-balteanu/redmine_tags master](https://github.com/marius-balteanu/redmine_tags/tree/master).

More commits still to come for fixing documentation / tests / Travis.
I also have some TODOs laying around.

@marius-balteanu @ixti @PowerKiKi can you please take a look?

### CODE REVIEW

**Comment by ixti** [comment]
:+1:

**Comment by PowerKiKi** [comment]
I won't be able to do anything until next week. But if somebody else would test and merge it before that, I wouldn't mind.

**Comment by ixti** [comment]
@sdwolf @marius-balteanu if you guys feel it good to go, please, go ahead and merge!

**Comment by sdwolf** [comment]
Not yet, there are a few things I still need to look into, expect some progress of the end of this week.

**Comment by sdwolf** [comment]
I think I eliminated the major blockers, @marius-balteanu as soon as you give me your :+1: this can be merged.

**Comment by PowerKiKi** [comment]
It seems to be mostly working fine except for bulk editing. We had a long discussion about this non-trivial matter in #57 and the temporary conclusion was to [disable bulk editing for tags](https://github.com/ixti/redmine_tags/issues/57#issuecomment-30926667).

In this PR bulk editing is available, but the behavior is IMHO wrong. When editing multiple issues with one or many tags and without changing anything in the form. Just submitting the form will delete all tags. Meaning that changing another non-related field will always delete tags. This behavior cannot be re-introduced and short of implementing a proper bulk-edit GUI, I'd re-disable it.

**Comment by sdwolf** [comment]
I added back that commit (I think it got lost in the merge).

**Pull request merged**
