### PR TITLE
Update copyrights

### PR DESCRIPTION
**Pull request by ixti**
@sdwolf  @marius-balteanu please take a look and merge if you like. Open to discussion.

### CODE REVIEW

**Comment by sdwolf** [comment]
:+1: for the "Glorious" part :smile:
For the file permissions part, did you ran into any problems and needed to change them manually? Or was it the case detaild [here](http://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha)?
I'd prefer we set `git config --global core.filemode false` and not make commits like that since our environments vary drastically and they may be abundant.

**Comment by ixti** [comment]
I did not ran into any problems. Just a little bit paranoid :D
I understand that we all run different environments. Just wanted to see all files with 0644 mode ;))
Agree on `git config --global core.filemode false`. AFAK it will drop executable bits.

**Comment by PowerKiKi** [comment]
For the permissions thing, `core.filemode` is no a good option IMHO. It only covers execute bit and never read/write bits. And since I am pretty sure nothing ever should be executable in this repository, it is indeed safer to not touch `core.filemode` and ensure that no files are executable. So merge this PR.

This `core.filemode` sounds like a good idea when you first hear about it, but if you read thoroughly [the documention](https://git-scm.com/docs/git-config), there are only very rare cases where it should actually be used.

**Comment by ixti** [comment]
@PowerKiKi `git config --global core.filemode false` doesn't change repo's behavior. It might a be a good change when you're on windows machine. But there's a trade off. In some cases you actually want some files to have executable bit... Fortunately it's not our case, so IMHO we should:

1. Ensure all files have no executable bit in this repo (this PR does that)
2. Devs on Windows machines might want to call `git config --local core.filemode false` while in repo.

**Comment by PowerKiKi** [comment]
I tend to forget that Windows is a possibility for web developers... but otherwise, I think we agree :)

**Comment by ixti** [comment]
I must admit, I also, sometimes forget that Linux is not the only OS...

**Comment by ixti** [comment]
@sdwolf so, if you hoave no strong objections against second patch in this PR (removing executable bit from some of the files in repo), let's merge this down :D

**Comment by sdwolf** [comment]
No objections but you missed a few in app/helpers and redmine_tags.css.

**Comment by ixti** [comment]
I don't see such:

```
❯ pwd && ls -la
/home/ixti/Projects/redmine_tags/app/helpers
total 28
drwxr-xr-x 2 ixti ixti 4096 Jan 14 23:32 .
drwxr-xr-x 5 ixti ixti 4096 Dec  8 13:49 ..
-rw-r--r-- 1 ixti ixti 2134 Dec 30 13:42 filters_helper.rb
-rw-r--r-- 1 ixti ixti 1382 Jan 14 23:32 issues_tags_helper.rb
-rw-r--r-- 1 ixti ixti 4536 Dec 30 13:41 tags_helper.rb
-rw-r--r-- 1 ixti ixti 1401 Jan 14 23:32 wiki_tags_helper.rb

❯ pwd && ls -la
/home/ixti/Projects/redmine_tags/assets/stylesheets
total 16
drwxr-xr-x 2 ixti ixti 4096 Dec  8 13:49 .
drwxr-xr-x 4 ixti ixti 4096 Dec  8 13:49 ..
-rw-r--r-- 1 ixti ixti 1412 Dec  8 13:49 jquery.tagit.css
-rw-r--r-- 1 ixti ixti 2829 Dec  8 13:49 redmine_tags.css
```

**Comment by ixti** [comment]
Here's full list of files I have now:

```
❯ find . -type f \! -path "./.git/*" -ls
  3938981     12 -rw-r--r--   1  ixti     ixti         8826 Dec  8 13:49 ./assets/javascripts/tag-it.min.js
  3938984      4 -rw-r--r--   1  ixti     ixti         1412 Dec  8 13:49 ./assets/stylesheets/jquery.tagit.css
  3938983      4 -rw-r--r--   1  ixti     ixti         2829 Dec  8 13:49 ./assets/stylesheets/redmine_tags.css
  3938505      4 -rw-r--r--   1  ixti     ixti          816 Jan 14 23:34 ./COPYING
  3938523      4 -rw-r--r--   1  ixti     ixti           83 Jan 14 23:35 ./lib/redmine_tags.rb
  3938946      4 -rw-r--r--   1  ixti     ixti         2170 Jan 14 23:36 ./lib/redmine_tags/hooks/views_wiki_hook.rb
  3938916      4 -rw-r--r--   1  ixti     ixti         1563 Jan 14 23:36 ./lib/redmine_tags/hooks/model_issue_hook.rb
  3938947      4 -rw-r--r--   1  ixti     ixti          352 Jan 14 23:36 ./lib/redmine_tags/hooks/views_issues_hook.rb
  3938941      4 -rw-r--r--   1  ixti     ixti          876 Jan 14 23:35 ./lib/redmine_tags/patches/queries_helper_patch.rb
  3938935      4 -rw-r--r--   1  ixti     ixti         2495 Jan 14 23:35 ./lib/redmine_tags/patches/wiki_page_patch.rb
  3938940      4 -rw-r--r--   1  ixti     ixti         1928 Jan 14 23:35 ./lib/redmine_tags/patches/issue_query_patch.rb
  3938918      4 -rw-r--r--   1  ixti     ixti          776 Jan 14 23:36 ./lib/redmine_tags/patches/auto_completes_controller_patch.rb
  3938939      4 -rw-r--r--   1  ixti     ixti         3512 Jan 14 23:35 ./lib/redmine_tags/patches/issue_patch.rb
  3938917      4 -rw-r--r--   1  ixti     ixti          488 Jan 14 23:36 ./lib/redmine_tags/patches/add_helpers_for_issue_tags_patch.rb
  3938938      4 -rw-r--r--   1  ixti     ixti          343 Jan 14 23:35 ./lib/redmine_tags/patches/wiki_controller_patch.rb
  3938504      4 -rw-r--r--   1  ixti     ixti         1714 Dec 30 13:39 ./README.md
  3938920      4 -rw-r--r--   1  ixti     ixti          141 Dec 30 13:37 ./config/database-mysql-travis.yml
  3938922      4 -rw-r--r--   1  ixti     ixti          488 Dec  8 13:49 ./config/routes.rb
  3938921      4 -rw-r--r--   1  ixti     ixti          135 Dec 30 13:37 ./config/database-postgresql-travis.yml
  3938930      4 -rw-r--r--   1  ixti     ixti          666 Jan 14 23:37 ./config/locales/pt.yml
  3938932      4 -rw-r--r--   1  ixti     ixti          644 Jan 14 23:37 ./config/locales/de.yml
  3938931      4 -rw-r--r--   1  ixti     ixti          663 Jan 14 23:38 ./config/locales/tr.yml
  3938926      4 -rw-r--r--   1  ixti     ixti          757 Jan 14 23:37 ./config/locales/zh-TW.yml
  3938924      4 -rw-r--r--   1  ixti     ixti          793 Jan 14 23:37 ./config/locales/en.yml
  3938927      4 -rw-r--r--   1  ixti     ixti          567 Jan 14 23:37 ./config/locales/zh.yml
  3938925      4 -rw-r--r--   1  ixti     ixti          681 Jan 14 23:38 ./config/locales/it.yml
  3938933      4 -rw-r--r--   1  ixti     ixti          903 Jan 14 23:37 ./config/locales/ru.yml
  3938948      4 -rw-r--r--   1  ixti     ixti          960 Jan 14 23:37 ./config/locales/bg.yml
  3938929      4 -rw-r--r--   1  ixti     ixti          592 Jan 14 23:37 ./config/locales/fr.yml
  3938502      4 -rw-r--r--   1  ixti     ixti           33 Dec 30 13:37 ./Gemfile
  3938506     32 -rw-r--r--   1  ixti     ixti        32422 Oct 23  2014 ./LICENSE
  3938913      4 -rw-r--r--   1  ixti     ixti         1871 Jan 14 23:32 ./app/controllers/tags_controller.rb
  3938914      4 -rw-r--r--   1  ixti     ixti         1382 Jan 14 23:32 ./app/helpers/issues_tags_helper.rb
  3938915      4 -rw-r--r--   1  ixti     ixti         1401 Jan 14 23:32 ./app/helpers/wiki_tags_helper.rb
  3938974      8 -rw-r--r--   1  ixti     ixti         4536 Dec 30 13:41 ./app/helpers/tags_helper.rb
  3938973      4 -rw-r--r--   1  ixti     ixti         2134 Dec 30 13:42 ./app/helpers/filters_helper.rb
  3938969      4 -rw-r--r--   1  ixti     ixti          246 Dec  8 13:49 ./app/views/issues/_tags_sidebar.html.erb
  3938971      4 -rw-r--r--   1  ixti     ixti         1437 Dec  8 13:49 ./app/views/issues/_tags_form.html.erb
  3938970      4 -rw-r--r--   1  ixti     ixti          296 Dec  8 13:49 ./app/views/issues/_tags.html.erb
  3938965      4 -rw-r--r--   1  ixti     ixti          238 Dec  8 13:49 ./app/views/wiki/_tags_sidebar.html.erb
  3938967      4 -rw-r--r--   1  ixti     ixti         1046 Dec  8 13:49 ./app/views/wiki/_tags_form.html.erb
  3938966      4 -rw-r--r--   1  ixti     ixti          239 Dec  8 13:49 ./app/views/wiki/_tags.html.erb
  3938956      4 -rw-r--r--   1  ixti     ixti           51 Dec  8 13:49 ./app/views/auto_completes/_tag_list.html.erb
  3938955      4 -rw-r--r--   1  ixti     ixti           51 Dec  8 13:49 ./app/views/auto_completes/_tag_list.json.erb
  3938960      4 -rw-r--r--   1  ixti     ixti          635 Dec  8 13:49 ./app/views/tags/merge.html.erb
  3938962      4 -rw-r--r--   1  ixti     ixti          537 Dec  8 13:49 ./app/views/tags/context_menu.html.erb
  3938963      4 -rw-r--r--   1  ixti     ixti         1289 Dec  8 13:49 ./app/views/tags/_manage_tags.html.erb
  3938958      4 -rw-r--r--   1  ixti     ixti          527 Dec  8 13:49 ./app/views/tags/edit.html.erb
  3938961      4 -rw-r--r--   1  ixti     ixti         1173 Dec  8 13:49 ./app/views/tags/_general.html.erb
  3938959      4 -rw-r--r--   1  ixti     ixti          272 Dec  8 13:49 ./app/views/tags/_settings.html.erb
  3938507      4 -rw-r--r--   1  ixti     ixti         1157 Jan 14 23:32 ./.travis.yml
  3938951      4 -rw-r--r--   1  ixti     ixti         2721 Dec 30 13:37 ./db/migrate/20151209153801_acts_as_taggable_migration.rb
  3940538      4 -rw-r--r--   1  ixti     ixti          766 Jan 14 23:35 ./init.rb
  3938975      4 -rw-r--r--   1  ixti     ixti         3585 Jan 14 23:32 ./spec/controllers/tags_controller_spec.rb
  3938976      4 -rw-r--r--   1  ixti     ixti          263 Jan 14 23:32 ./spec/controllers/wiki_controller_patach_spec.rb
  3938943      4 -rw-r--r--   1  ixti     ixti          423 Jan 14 23:32 ./spec/controllers/add_helpers_for_issue_tags_patch_spec.rb
  3938944      4 -rw-r--r--   1  ixti     ixti          299 Jan 14 23:32 ./spec/controllers/auto_completes_controller_patch_spec.rb
  3938513      8 -rw-r--r--   1  ixti     ixti         6659 Jan 14 23:32 ./spec/models/issue_patch_spec.rb
  3938514      4 -rw-r--r--   1  ixti     ixti          234 Dec 30 13:37 ./spec/models/wiki_page_patch_spec.rb
  3940530      4 -rw-r--r--   1  ixti     ixti          254 Jan 14 23:32 ./spec/models/queries_helper_patch_spec.rb
  3938978      4 -rw-r--r--   1  ixti     ixti          242 Jan 14 23:32 ./spec/models/issue_query_patch_spec.rb
  3938511      4 -rw-r--r--   1  ixti     ixti           80 Dec 30 13:37 ./spec/spec_helper.rb
  3940534      4 -rw-r--r--   1  ixti     ixti          412 Jan 14 23:32 ./spec/support/setup_support.rb
  3940533      4 -rw-r--r--   1  ixti     ixti          157 Jan 14 23:32 ./spec/support/login_support.rb
  3938509      4 -rw-r--r--   1  ixti     ixti           12 Dec 30 13:37 ./.gitignore
  3938501      4 -rw-r--r--   1  ixti     ixti          892 Oct 23  2014 ./.rubocop.yml
```

**Pull request merged**
